#
# Commented sections of this configuration should be uncommented once
# luarocks is added to the apt package whitelist:
#   https://github.com/travis-ci/travis-ci/issues/3716
#
sudo: false
branches:
  only:
    - master
cache:
  apt: true
  directories:
    - src/oc-id/vendor/bundle
#    - $HOME/.luarocks/rocks
    - $HOME/.cpanm
    - $HOME/.cpan
    - $HOME/perl5
before_cache:
  # Prevent build log from changing cache cand causing repackage
  - rm -f $HOME/.cpanm/work/*/build.log
  - rm -f $HOME/.cpanm/build.log
language: erlang
otp_release:
  - R16B03-1
  - 17.0
  - 17.1
  - 17.2
  - 17.3
  - 17.4
  - 17.5

addons:
  postgresql: "9.3"
  apt:
    sources:
      - chef-stable-precise
    packages:
      - cpanminus
      - perl
#      - lua5.1
      - libdbd-pg-perl
      - build-essential
      - chefdk
env:
  global:
    - PERL5LIB=~/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:~/perl5/lib/perl5:/etc/perl:/usr/local/lib/perl/5.14.2:/usr/local/share/perl/5.14.2:/usr/lib/perl5:/usr/share/perl5:/usr/lib/perl/5.14:/usr/share/perl/5.14:/usr/local/lib/site_perl
    - USE_OMNIBUS_FILES=0
    - CHEFDK_GECODE_PATH=/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode

#    - LUALIB=~/.luarocks/lib/lua/5.2
  matrix:
    # - COMPONENT=omnibus
  - COMPONENT=src/oc_erchef
  - COMPONENT=src/oc-id
  - COMPONENT=src/chef-mover
install:
#  - sudo apt-get install luarocks
#  - luarocks install --local lpeg
#  - luarocks install --local lua-cjson
#  - eval $(luarocks path)
  - rvm install --binary 2.1.4
  - rvm use 2.1.4
  - cpanm --notest --quiet --local-lib=$HOME/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --notest --quiet App::Sqitch
  - cd $COMPONENT && travis_retry make install

script:
  - USE_SYSTEM_GECODE=1 LIBRARY_PATH=$CHEFDK_GECODE_PATH/lib LD_LIBRARY_PATH=$CHEFDK_GECODE_PATH/lib CPLUS_INCLUDE_PATH=$CHEFDK_GECODE_PATH/include make travis
